#!/bin/bash

set -e

if [ "$1" = "usage" ]; then
  echo "    newd"
  echo "      Creates a dialog for adding a new todo."
  exit 0
fi

result=$(yad --title="Add new todo.txt item" --separator="" --form --field="Todo")

todo.sh add "$result"
